### ISSUE TITLE
Login endpoint url for mhgui is invalid

### ISSUE THREAD

**Issue by f3lang** [congruity/congruity#2]
Hi there!

i just tried to get mhgui working and it is stuck with the message "Login Failed. Not found"
I tracked it down to mhmanager.py line 184-189. Looks like the service returns a 404 
on the request and therefore the login is failing.

**Comment by swt2c** [comment]
I'm able to log in without any problems.

What version of congruity/mhgui are you using?

**Comment by swt2c** [comment]
Closing due to lack of response.

**Comment by penguinjeff** [comment]
I am getting this error and am using version 20? at least that is what is displayed on the titlebar for mhgui.

"MHGUI version 20" is what is on the titlebar. strange that it doesn't have a -v or --version option.
