### ISSUE TITLE
Congruity failure to notify website

### ISSUE THREAD

**Issue by Craig-Powell** [congruity/congruity#7]
Went to update my 880 today and Congruity threw an error when it got to the notify website step.  (Fedora 37 workstation) These are the details offered:

```
OS-level error related to network operations
    (libconcord function post_connect_test_success error 13)

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/congruity/congruity.py", line 721, in _WorkerFunction
    self._WorkerFunctionBody()
  File "/usr/lib/python3.11/site-packages/congruity/congruity.py", line 801, in _WorkerFunctionBody
    libconcord.post_connect_test_success(
  File "/usr/lib/python3.11/site-packages/libconcord.py", line 126, in __call__
    raise LibConcordException(self.func_name, result)
libconcord.LibConcordException: libconcord function 'post_connect_test_success' failed with error code 13 ('OS-level error related to network operations')
```

Coincidentally, the members.harmonyremote.com certificate expired 4 days ago.  I'm assuming Logitech has opted to no longer maintain this as they have ceased support (aside from keeping the website online) of the remotes.  I've already allowed the certificate exception in Firefox, but is it something that needs to be ignored elsewhere too?

**Comment by swt2c** [comment]
The expired cert is very likely the reason for the failure.  It looks like they are using a Let's Encrypt certificate, so hopefully this just means their renewal process didn't run for some reason and they'll hopefully fix it relatively soon?  Unfortunately, to work around this, it would have to be done in concordance.  I'd rather not try to change anything unless this stays broken for a while, though.

**Comment by Craig-Powell** [comment]
Ugh, understood and thanks. I just changed my receiver in my main entertainment center, luckily I got the rough setup in last week.  Just trying to tweak it but I can live with that for now.  I am open to suggestions if anyone knows of a workaround I can do locally.

**Comment by swt2c** [comment]
Nothing to be done in congruity.  See https://github.com/jaymzh/concordance/issues/48.

**Comment by Craig-Powell** [comment]
As mentioned in [jaymzh/concordance#48](https://github.com/jaymzh/concordance/issues/48), this is now "fixed" for concordance by Logitech (I assume) updating their cert.  It is currently only good for until June though so I'm not holding my breath that we don't see this again.  Marking this as closed/resolved and if it does show back up in the future I know to look at concordance.

**Comment by swt2c** [comment]
> As mentioned in [jaymzh/concordance#48](https://github.com/jaymzh/concordance/issues/48), this is now "fixed" for concordance by Logitech (I assume) updating their cert. It is currently only good for until June though so I'm not holding my breath that we don't see this again. Marking this as closed/resolved and if it does show back up in the future I know to look at concordance.

Yes, that's how long Let's Encrypt certificates are usually valid for (90 days).  Most likely their automated renewal process failed for some reason.
